version: 2

builds:
  - binary: tmux-launcher
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"

brews:
  - repository:
      owner: martinlindner
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/martinlindner/tmux-launcher
    description: A smart tmux wrapper that automatically manages session attachment
    license: MIT
